import type { PackageWithSection } from '@/lib/packages/types'

/** Shown when the database is unreachable — keeps the storefront populated. */
export const FALLBACK_PACKAGES: PackageWithSection[] = [
  {
    id: 'fallback-official-25',
    section_id: null,
    name_ar: 'باقة استقبال رسمي',
    name_en: 'Official Reception',
    hours_per_visit: 3,
    visits_per_week: 25,
    visits_per_month: 25,
    price_omr: '85.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 1,
    created_at: null,
    updated_at: null,
    section_slug: 'official',
    section_name_ar: 'ضيافة رسمية',
    section_name_en: 'Official hospitality',
  },
  {
    id: 'fallback-official-50',
    section_id: null,
    name_ar: 'باقة اجتماعات حكومية',
    name_en: 'Government Meetings',
    hours_per_visit: 4,
    visits_per_week: 50,
    visits_per_month: 50,
    price_omr: '145.00',
    is_active: true,
    is_popular: true,
    is_featured: true,
    sort_order: 2,
    created_at: null,
    updated_at: null,
    section_slug: 'official',
    section_name_ar: 'ضيافة رسمية',
    section_name_en: 'Official hospitality',
  },
  {
    id: 'fallback-official-100',
    section_id: null,
    name_ar: 'باقة مؤتمر مصغّر',
    name_en: 'Mini Conference',
    hours_per_visit: 6,
    visits_per_week: 100,
    visits_per_month: 100,
    price_omr: '280.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 3,
    created_at: null,
    updated_at: null,
    section_slug: 'official',
    section_name_ar: 'ضيافة رسمية',
    section_name_en: 'Official hospitality',
  },
  {
    id: 'fallback-corp-30',
    section_id: null,
    name_ar: 'باقة ضيافة مكتبية',
    name_en: 'Office Hospitality',
    hours_per_visit: 3,
    visits_per_week: 30,
    visits_per_month: 30,
    price_omr: '95.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 4,
    created_at: null,
    updated_at: null,
    section_slug: 'corporate',
    section_name_ar: 'ضيافة شركات',
    section_name_en: 'Corporate hospitality',
  },
  {
    id: 'fallback-corp-75',
    section_id: null,
    name_ar: 'باقة ورشة عمل',
    name_en: 'Workshop Package',
    hours_per_visit: 5,
    visits_per_week: 75,
    visits_per_month: 75,
    price_omr: '210.00',
    is_active: true,
    is_popular: true,
    is_featured: true,
    sort_order: 5,
    created_at: null,
    updated_at: null,
    section_slug: 'corporate',
    section_name_ar: 'ضيافة شركات',
    section_name_en: 'Corporate hospitality',
  },
  {
    id: 'fallback-corp-150',
    section_id: null,
    name_ar: 'باقة فعالية شركات',
    name_en: 'Corporate Event',
    hours_per_visit: 8,
    visits_per_week: 150,
    visits_per_month: 150,
    price_omr: '420.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 6,
    created_at: null,
    updated_at: null,
    section_slug: 'corporate',
    section_name_ar: 'ضيافة شركات',
    section_name_en: 'Corporate hospitality',
  },
  {
    id: 'fallback-open-80',
    section_id: null,
    name_ar: 'باقة افتتاح أنيق',
    name_en: 'Elegant Opening',
    hours_per_visit: 5,
    visits_per_week: 80,
    visits_per_month: 80,
    price_omr: '250.00',
    is_active: true,
    is_popular: true,
    is_featured: true,
    sort_order: 7,
    created_at: null,
    updated_at: null,
    section_slug: 'openings',
    section_name_ar: 'افتتاحات ومناسبات',
    section_name_en: 'Openings & occasions',
  },
  {
    id: 'fallback-open-200',
    section_id: null,
    name_ar: 'باقة مناسبة كبرى',
    name_en: 'Grand Occasion',
    hours_per_visit: 8,
    visits_per_week: 200,
    visits_per_month: 200,
    price_omr: '650.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 8,
    created_at: null,
    updated_at: null,
    section_slug: 'openings',
    section_name_ar: 'افتتاحات ومناسبات',
    section_name_en: 'Openings & occasions',
  },
  {
    id: 'fallback-morning-40',
    section_id: null,
    name_ar: 'باقة ضيافة صباحية',
    name_en: 'Morning Hospitality',
    hours_per_visit: 2,
    visits_per_week: 40,
    visits_per_month: 40,
    price_omr: '110.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 9,
    created_at: null,
    updated_at: null,
    section_slug: 'official',
    section_name_ar: 'ضيافة رسمية',
    section_name_en: 'Official hospitality',
  },
  {
    id: 'fallback-coffee-60',
    section_id: null,
    name_ar: 'باقة قهوة واستقبال',
    name_en: 'Coffee Reception',
    hours_per_visit: 3,
    visits_per_week: 60,
    visits_per_month: 60,
    price_omr: '130.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 10,
    created_at: null,
    updated_at: null,
    section_slug: 'corporate',
    section_name_ar: 'ضيافة شركات',
    section_name_en: 'Corporate hospitality',
  },
  {
    id: 'fallback-signing-120',
    section_id: null,
    name_ar: 'باقة حفل توقيع',
    name_en: 'Signing Ceremony',
    hours_per_visit: 4,
    visits_per_week: 120,
    visits_per_month: 120,
    price_omr: '320.00',
    is_active: true,
    is_popular: false,
    is_featured: false,
    sort_order: 11,
    created_at: null,
    updated_at: null,
    section_slug: 'openings',
    section_name_ar: 'افتتاحات ومناسبات',
    section_name_en: 'Openings & occasions',
  },
]
