import type { CatalogService, PackageEnrichment } from '@/lib/experience/types'

export const CATALOG_SERVICES: CatalogService[] = [
  {
    id: 'arabic-coffee',
    name_ar: 'خدمة القهوة العربية',
    name_en: 'Arabic Coffee Service',
    description_ar: 'قهوة عربية تقليدية مع تقديم احترافي.',
    description_en: 'Traditional Arabic coffee service with professional serving.',
    category: 'food_beverage',
    price_omr: 45,
  },
  {
    id: 'tea',
    name_ar: 'خدمة الشاي',
    name_en: 'Tea Service',
    description_ar: 'تشكيلة شاي مناسبة للاستقبال والاجتماعات.',
    description_en: 'A refined tea selection for receptions and meetings.',
    category: 'food_beverage',
    price_omr: 25,
  },
  {
    id: 'dates',
    name_ar: 'تمور ومقبلات خفيفة',
    name_en: 'Dates & Light Bites',
    description_ar: 'تمور فاخرة ومقبلات خفيفة للترحيب.',
    description_en: 'Premium dates and light welcome bites.',
    category: 'food_beverage',
    price_omr: 30,
  },
  {
    id: 'water',
    name_ar: 'مياه ومشروبات باردة',
    name_en: 'Water & Soft Drinks',
    description_ar: 'مياه ومشروبات باردة طوال مدة المناسبة.',
    description_en: 'Still water and soft drinks throughout the occasion.',
    category: 'food_beverage',
    price_omr: 20,
  },
  {
    id: 'juices',
    name_ar: 'عصائر طازجة',
    name_en: 'Fresh Juices',
    description_ar: 'محطة عصائر طازجة للضيوف.',
    description_en: 'A fresh juice station for guests.',
    category: 'food_beverage',
    price_omr: 55,
  },
  {
    id: 'desserts',
    name_ar: 'محطة حلويات',
    name_en: 'Dessert Station',
    description_ar: 'تشكيلة حلويات أنيقة تناسب المناسبة.',
    description_en: 'An elegant dessert selection for the occasion.',
    category: 'food_beverage',
    price_omr: 75,
  },
  {
    id: 'canapes',
    name_ar: 'كانابيهات',
    name_en: 'Canapés',
    description_ar: 'مقبلات راقية تقدَّم أثناء الاستقبال.',
    description_en: 'Refined canapés served during reception.',
    category: 'food_beverage',
    price_omr: 90,
  },
  {
    id: 'buffet',
    name_ar: 'بوفيه',
    name_en: 'Buffet',
    description_ar: 'بوفيه ضيافة مرن حسب عدد الضيوف.',
    description_en: 'A flexible hospitality buffet scaled to guest count.',
    category: 'food_beverage',
    price_omr: 150,
  },
  {
    id: 'tables',
    name_ar: 'طاولات',
    name_en: 'Tables',
    description_ar: 'تجهيز طاولات مناسبة لشكل المناسبة.',
    description_en: 'Tables arranged to suit the occasion layout.',
    category: 'setup',
    price_omr: 40,
  },
  {
    id: 'chairs',
    name_ar: 'كراسي',
    name_en: 'Chairs',
    description_ar: 'كراسي مريحة بعدد الضيوف.',
    description_en: 'Comfortable seating matched to guest count.',
    category: 'setup',
    price_omr: 35,
  },
  {
    id: 'serving-station',
    name_ar: 'محطة تقديم',
    name_en: 'Serving Station',
    description_ar: 'محطة تقديم منظمة للمشروبات والمقبلات.',
    description_en: 'An organized serving station for drinks and bites.',
    category: 'setup',
    price_omr: 50,
  },
  {
    id: 'decorative-setup',
    name_ar: 'تجهيز ديكوري',
    name_en: 'Decorative Setup',
    description_ar: 'لمسات ديكور بسيطة وأنيقة.',
    description_en: 'Simple, elegant decorative touches.',
    category: 'setup',
    price_omr: 80,
  },
  {
    id: 'welcome-area',
    name_ar: 'منطقة ترحيب',
    name_en: 'Welcome Area',
    description_ar: 'منطقة استقبال واضحة للضيوف.',
    description_en: 'A clear welcome area for arriving guests.',
    category: 'setup',
    price_omr: 60,
  },
  {
    id: 'servers',
    name_ar: 'طاقم تقديم',
    name_en: 'Servers',
    description_ar: 'طاقم تقديم محترف طوال المناسبة.',
    description_en: 'Professional servers throughout the occasion.',
    category: 'staff',
    price_omr: 70,
  },
  {
    id: 'hosts',
    name_ar: 'مستقبلون',
    name_en: 'Hosts',
    description_ar: 'فريق استقبال يرحب بالضيوف ويوجّههم.',
    description_en: 'Hosts who welcome and guide guests.',
    category: 'staff',
    price_omr: 55,
  },
  {
    id: 'supervisors',
    name_ar: 'مشرفون',
    name_en: 'Supervisors',
    description_ar: 'إشراف ميداني لضمان سلاسة التنفيذ.',
    description_en: 'On-site supervision for smooth delivery.',
    category: 'staff',
    price_omr: 65,
  },
  {
    id: 'event-staff',
    name_ar: 'طاقم فعالية',
    name_en: 'Event Staff',
    description_ar: 'دعم تشغيلي إضافي للمناسبات الأكبر.',
    description_en: 'Extra operational support for larger occasions.',
    category: 'staff',
    price_omr: 90,
  },
  {
    id: 'welcome-team',
    name_ar: 'فريق ترحيب',
    name_en: 'Welcome Team',
    description_ar: 'فريق مخصص للترحيب وتنظيم الدخول.',
    description_en: 'A dedicated team for greeting and entry flow.',
    category: 'additional',
    price_omr: 40,
  },
  {
    id: 'cleaning',
    name_ar: 'تنظيف بعد المناسبة',
    name_en: 'Post-event Cleaning',
    description_ar: 'تنظيف الموقع بعد انتهاء الضيافة.',
    description_en: 'Venue tidy-up after hospitality ends.',
    category: 'additional',
    price_omr: 50,
  },
  {
    id: 'transportation',
    name_ar: 'نقل وتوصيل',
    name_en: 'Transportation',
    description_ar: 'نقل التجهيزات والطاقم من وإلى الموقع.',
    description_en: 'Transport for setup and staff to/from the venue.',
    category: 'additional',
    price_omr: 45,
  },
  {
    id: 'special-requests',
    name_ar: 'طلبات خاصة',
    name_en: 'Special Requests',
    description_ar: 'مرونة لتفاصيل إضافية حسب احتياجكم.',
    description_en: 'Flexibility for extra details unique to your occasion.',
    category: 'additional',
    price_omr: 35,
  },
]

const COVER = '/images/brand/brand-table.webp'
const UNIFORM = '/images/brand/brand-uniform.webp'

/** Enrichment keyed by English package name (normalized). */
export const PACKAGE_ENRICHMENT: Record<string, PackageEnrichment> = {
  'official reception': {
    slug: 'official-reception',
    description_ar: 'تجربة استقبال رسمي أنيقة للاجتماعات والمناسبات الحكومية.',
    description_en: 'An elegant official reception experience for meetings and government occasions.',
    category: 'government',
    occasion_types: ['government', 'meeting'],
    min_guests: 15,
    max_guests: 40,
    per_guest_omr: 2.5,
    features_ar: ['مشروبات ترحيب', 'قهوة عربية', 'تمور', 'طاقم تقديم'],
    features_en: ['Welcome drinks', 'Arabic coffee', 'Dates', 'Service staff'],
    included_service_ids: ['arabic-coffee', 'dates', 'tea', 'servers'],
    recommended_service_ids: ['welcome-area', 'hosts'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'government meetings': {
    slug: 'government-meetings',
    description_ar: 'ضيافة منظمة للاجتماعات الحكومية باهتمام بالتفاصيل الرسمية.',
    description_en: 'Organized hospitality for government meetings with care for official detail.',
    category: 'government',
    occasion_types: ['government', 'meeting'],
    min_guests: 30,
    max_guests: 80,
    per_guest_omr: 2.2,
    features_ar: ['قهوة عربية', 'شاي', 'تمور', 'محطة تقديم', 'مشرف'],
    features_en: ['Arabic coffee', 'Tea', 'Dates', 'Serving station', 'Supervisor'],
    included_service_ids: ['arabic-coffee', 'tea', 'dates', 'serving-station', 'supervisors'],
    recommended_service_ids: ['water', 'hosts'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
    is_recommended: true,
    badge_ar: 'الأكثر اختيارًا للمناسبات المتوسطة',
    badge_en: 'Most chosen for mid-size occasions',
  },
  'mini conference': {
    slug: 'mini-conference',
    description_ar: 'تجربة ضيافة متكاملة للمؤتمرات المصغّرة والفعاليات الرسمية.',
    description_en: 'A complete hospitality experience for mini conferences and formal events.',
    category: 'events',
    occasion_types: ['government', 'events', 'corporate'],
    min_guests: 70,
    max_guests: 140,
    per_guest_omr: 2,
    features_ar: ['مشروبات', 'مقبلات', 'محطة تقديم', 'طاقم فعالية', 'منطقة ترحيب'],
    features_en: ['Beverages', 'Light bites', 'Serving station', 'Event staff', 'Welcome area'],
    included_service_ids: ['arabic-coffee', 'water', 'canapes', 'serving-station', 'event-staff'],
    recommended_service_ids: ['welcome-area', 'decorative-setup'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'office hospitality': {
    slug: 'office-hospitality',
    description_ar: 'ضيافة مرنة للاجتماعات اليومية والمناسبات المكتبية.',
    description_en: 'Flexible hospitality for day-to-day meetings and office occasions.',
    category: 'corporate',
    occasion_types: ['corporate', 'meeting'],
    min_guests: 15,
    max_guests: 45,
    per_guest_omr: 2.4,
    features_ar: ['قهوة', 'شاي', 'مياه', 'طاقم تقديم'],
    features_en: ['Coffee', 'Tea', 'Water', 'Service staff'],
    included_service_ids: ['arabic-coffee', 'tea', 'water', 'servers'],
    recommended_service_ids: ['dates'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'workshop package': {
    slug: 'workshop-hospitality',
    description_ar: 'ضيافة مناسبة لورش العمل والجلسات التدريبية.',
    description_en: 'Hospitality suited to workshops and training sessions.',
    category: 'corporate',
    occasion_types: ['corporate', 'meeting'],
    min_guests: 25,
    max_guests: 70,
    per_guest_omr: 2.1,
    features_ar: ['مشروبات', 'مقبلات خفيفة', 'محطة تقديم'],
    features_en: ['Beverages', 'Light bites', 'Serving station'],
    included_service_ids: ['tea', 'water', 'dates', 'serving-station'],
    recommended_service_ids: ['arabic-coffee', 'servers'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'corporate event': {
    slug: 'corporate-event',
    description_ar: 'تجربة ضيافة متكاملة لفعاليات الشركات.',
    description_en: 'A complete hospitality experience for corporate events.',
    category: 'corporate',
    occasion_types: ['corporate', 'events', 'celebration'],
    min_guests: 50,
    max_guests: 150,
    per_guest_omr: 2.3,
    features_ar: ['مشروبات ترحيب', 'كانابيهات', 'طاقم تقديم', 'منطقة ترحيب', 'ديكور'],
    features_en: ['Welcome drinks', 'Canapés', 'Servers', 'Welcome area', 'Decor'],
    included_service_ids: ['arabic-coffee', 'canapes', 'servers', 'welcome-area', 'decorative-setup'],
    recommended_service_ids: ['desserts', 'hosts'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
    is_recommended: true,
    badge_ar: 'موصى بها لفعاليات الشركات',
    badge_en: 'Recommended for corporate events',
  },
  'elegant opening': {
    slug: 'elegant-opening',
    description_ar: 'ضيافة أنيقة للافتتاحات والمناسبات الخاصة.',
    description_en: 'Elegant hospitality for openings and special occasions.',
    category: 'private',
    occasion_types: ['private', 'celebration', 'events'],
    min_guests: 40,
    max_guests: 120,
    per_guest_omr: 2.5,
    features_ar: ['ترحيب', 'حلويات', 'ديكور', 'مستقبلون'],
    features_en: ['Welcome', 'Desserts', 'Decor', 'Hosts'],
    included_service_ids: ['welcome-team', 'desserts', 'decorative-setup', 'hosts'],
    recommended_service_ids: ['juices', 'canapes'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'grand occasion': {
    slug: 'grand-occasion',
    description_ar: 'حلول متكاملة للمناسبات الكبيرة التي تحتاج تنظيمًا دقيقًا.',
    description_en: 'Integrated solutions for large occasions that need precise coordination.',
    category: 'large',
    occasion_types: ['large', 'events', 'celebration', 'corporate'],
    min_guests: 120,
    max_guests: 300,
    per_guest_omr: 1.8,
    features_ar: ['بوفيه', 'طاقم فعالية', 'محطات تقديم', 'إشراف', 'تنظيف'],
    features_en: ['Buffet', 'Event staff', 'Serving stations', 'Supervision', 'Cleaning'],
    included_service_ids: ['buffet', 'event-staff', 'serving-station', 'supervisors', 'cleaning'],
    recommended_service_ids: ['transportation', 'decorative-setup'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'morning hospitality': {
    slug: 'morning-hospitality',
    description_ar: 'ضيافة صباحية خفيفة للاجتماعات والاستقبالات.',
    description_en: 'Light morning hospitality for meetings and receptions.',
    category: 'meeting',
    occasion_types: ['meeting', 'corporate', 'government'],
    min_guests: 10,
    max_guests: 40,
    per_guest_omr: 2.6,
    features_ar: ['قهوة', 'شاي', 'تمور', 'مياه'],
    features_en: ['Coffee', 'Tea', 'Dates', 'Water'],
    included_service_ids: ['arabic-coffee', 'tea', 'dates', 'water'],
    recommended_service_ids: ['servers'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'coffee reception': {
    slug: 'coffee-reception',
    description_ar: 'تجربة قهوة واستقبال سريعة وأنيقة.',
    description_en: 'A quick, elegant coffee and reception experience.',
    category: 'corporate',
    occasion_types: ['corporate', 'meeting', 'private'],
    min_guests: 15,
    max_guests: 50,
    per_guest_omr: 2.3,
    features_ar: ['قهوة عربية', 'شاي', 'تمور', 'طاقم تقديم'],
    features_en: ['Arabic coffee', 'Tea', 'Dates', 'Service staff'],
    included_service_ids: ['arabic-coffee', 'tea', 'dates', 'servers'],
    recommended_service_ids: ['welcome-area'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
  'signing ceremony': {
    slug: 'signing-ceremony',
    description_ar: 'ضيافة راقية لحفلات التوقيع والمناسبات الرسمية المختصرة.',
    description_en: 'Refined hospitality for signing ceremonies and concise official occasions.',
    category: 'events',
    occasion_types: ['government', 'corporate', 'events'],
    min_guests: 30,
    max_guests: 90,
    per_guest_omr: 2.4,
    features_ar: ['ترحيب', 'قهوة', 'مقبلات', 'مستقبلون', 'ديكور'],
    features_en: ['Welcome', 'Coffee', 'Bites', 'Hosts', 'Decor'],
    included_service_ids: ['welcome-team', 'arabic-coffee', 'canapes', 'hosts', 'decorative-setup'],
    recommended_service_ids: ['juices', 'supervisors'],
    cover_image: COVER,
    gallery: [COVER, UNIFORM],
  },
}

export function normalizePackageKey(nameEn: string) {
  return nameEn.trim().toLowerCase()
}

export function getServiceById(id: string) {
  return CATALOG_SERVICES.find((s) => s.id === id)
}

export function getServicesByCategory(category: CatalogService['category']) {
  return CATALOG_SERVICES.filter((s) => s.category === category)
}
